### PR TITLE
Add listener example

### PR DESCRIPTION
**Pull request by anuaimi**
add an example of how to capture and process events from chrome

### CODE REVIEW

**Comment by mvdan** [comment]
https://godoc.org/github.com/chromedp/chromedp already has two ListenTarget examples - do you think more are necessary?

**Comment by anuaimi** [comment]
A couple of comments.
- I'm very new to the chomedp and the chrome debug protocol.  A lot of the desire for this example was the difficult ramp I had
- can you clarify which examples have ListenTarget as I searched the code for that string and didn't come across any examples with it.
- I think the concept of how to use ListenTarget could be better documented.  I know it took me a couple of hours to finally figure it out.  In the end, I found a sample in an old issue https://github.com/chromedp/chromedp/issues/105 and that's what drove me to want to have a more explicit example that would be easier for new users to find
- I think its common to want to get the response headers (and status code). Maybe the headers example can be updated to not only do the request headers but also the response headers.  I'll be willing to update the example if you thought was the right way to go

**Comment by anuaimi** [comment]
Re-read your response.  I never came across the examples in the docs.  Once I found the /examples repo, I never thought to look in the docs.  Funny enough, I trolled through old issues trying to find a simple issue, which is where I found the source for the pull request.  There was someone else who wanted to get the response headers and couldn't figure out how to do it.  Is there any harm in having a ListenTarget sample in the examples repo?

**Comment by mvdan** [comment]
There's no harm in more examples per se, but I don't want to have duplicate examples in both places. The godoc page already has two ListenTarget examples, so I think that's plenty for now.

You're right that the two places are a bit confusing, though. I'll make sure to add links in both directions, to ensure others find them more easily.

**Comment by marco-m** [comment]
> https://godoc.org/github.com/chromedp/chromedp already has two ListenTarget examples - do you think more are necessary?

Hello @mvdan, I came here after a long Google search trying to understand how to get the body of a HTTP response with chromedp.

My 2 cents: from the point of view of a user new to chromedp and browser automation technologies in general, the existing 2 examples in the docs above are not easy to find at all. Also if I had stumbled upon them, I would not have understood them, while I read all the examples in this repo.

Thanks @anuaimi for the effort :-) and thanks to the chromedp team, this project is helping me a lot!

**Pull request closed without merging**
